title: W&M D3i Group Page
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://wmd3i.github.io

aux_links:
  Template Repository: https://github.com/wmd3i/wmd3i.github.io
